connectionStrings:
    defaultConnection: Server=(localdb)\\mssqllocaldb;Database=aspnet-CookieManagerTest-c32569c5-4c52-46fa-ab26-c4f4c4280f8a;Trusted_Connection=True;MultipleActiveResultSets=true
logging:
    includeScopes: false
    logLevel:
      default: Warning